import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Check if we're in E2E test mode (set via environment variable)
const isE2ETestMode = process.env.NEXT_PUBLIC_E2E_TEST_MODE === "true";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        {isE2ETestMode ? (
          // In E2E test mode, skip CopilotKit to avoid agent connection issues
          children
        ) : (
          <CopilotKit runtimeUrl="/api/copilotkit" agent="org_chat_agent" showDevConsole={false}>
            {children}
          </CopilotKit>
        )}
      </body>
    </html>
  );
}
